# docker build -t commonera/node:utopic .
# https://registry.hub.docker.com/u/jprjr/stackbrew-node/
# https://registry.hub.docker.com/u/jprjr/stackbrew-node/dockerfile
# https://registry.hub.docker.com/_/node/
# https://github.com/docker-library

FROM commonera/python:utopic

RUN apt-get install -y nodejs npm node-oauth-sign
